# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .Net back end build and test

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest
  
    steps:
    - name: Get repo code
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: Backend/dotNetBackend
    - name: Build
      run: dotnet build --no-restore
      working-directory: Backend/dotNetBackend
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: Backend/dotNetBackend
